services:
  facade-service:
    build: ./facade-service
    ports:
      - "3000:3000"
    environment:
      - LOGGING_SERVICE_URL=http://logging-service:3001
      - COUNTER_SERVICE_URL=http://counter-service:3002
    depends_on:
      - logging-service
      - counter-service

  logging-service:
    build: ./logging-service
    ports:
      - "3001:3001"

  counter-service:
    build: ./counter-service
    ports:
      - "3002:3002"
